---
# tasks file for web

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Install Php libaries.
  apt:
    name: "{{ item }}"
  with_items: "{{ php_extensions }}"

- name: Ensure pecl is installed (if configured).
  package:
    name: "php-pear"
    state: present

- name: Install PECL libaries.
  shell: "yes '' | {{ php_pecl_install_command }} {{ item }}"
  register: pecl_result
  changed_when: pecl_result is succeeded
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: "{{ php_pecl_extensions }}"

- name: Enable Memcache in cli
  shell: bash -c "echo extension=memcache.so > /etc/php/{{ php_version }}/cli/conf.d/memcache.ini"

- name: Enable Memcache in fpm
  shell: bash -c "echo extension=memcache.so > /etc/php/{{ php_version }}/fpm/conf.d/memcache.ini"

- name: Install Memcached
  apt:
    name: memcached
    state: latest

- name: Configure php.ini
  blockinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    block: |
      date.time = Asia/Jakarta
      cgi-fix_pathinfo = 0
      extension=memcache
    backup: yes
  notify: restart php-fpm

- name: Create Nginx virtual host
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: Create web-root directory
  file:
    path: /var/www/{{ domain_name }}
    state: directory

- name: Upload index.html and info.php files
  template:
    src: index.php.j2
    dest: /var/www/{{ domain_name }}/index.php

- name: Upload mysql.php files
  template:
    src: mysql.php.j2
    dest: /var/www/{{ domain_name }}/mysql.php

- name: Upload mssql.php files
  template:
    src: mssql.php.j2
    dest: /var/www/{{ domain_name }}/mssql.php

- name: Upload memcached.php files
  template:
    src: memcached.php.j2
    dest: /var/www/{{ domain_name }}/memcached.php
