---
# tasks file for web

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Install Php libaries.
  apt:
    name: "{{ item }}"
  with_items: "{{ php_extensions }}"

- name: Ensure pecl is installed (if configured).
  package:
    name: "php-pear"
    state: present

- name: Install PECL libaries.
  shell: "yes '' | {{ php_pecl_install_command }} {{ item }}"
  register: pecl_result
  changed_when: pecl_result is succeeded
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: "{{ php_pecl_extensions }}"

- name: install gnupg2
  apt:
    name: gnupg2

- name: install cert
  shell: curl -s https://packages.microsoft.com/keys/microsoft.asc | apt-key add - 

- name: update repo list
  shell: bash -c "curl -s https://packages.microsoft.com/config/ubuntu/{{ os_version }}/prod.list > /etc/apt/sources.list.d/mssql-release.list"

- name: update
  shell: apt-get update

- name: install mssql packages
  shell: ACCEPT_EULA=Y ACCEPT_EULA=Y apt-get -y install msodbcsql17 mssql-tools

# - name: Enable php in cli
#   shell: bash -c "echo extension={{ item }}.so > /etc/php/{{ php_version }}/cli/conf.d/{{ item }}.ini"
#   with_items:
#    - sqlsrv
#    - pdo_sqlsrv
#    - memcache

- name: Enable php in fpm
  shell: bash -c "echo extension={{ item }}.so > /etc/php/{{ php_version }}/fpm/conf.d/{{ item }}.ini"
  with_items:
   - sqlsrv
   - pdo_sqlsrv
   - memcache

- name: Install Memcached
  apt:
    name: memcached
    state: latest
  
- name: Configure php.ini
  blockinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    block: |
      date.time = Asia/Jakarta
      cgi-fix_pathinfo = 0
      extension=memcache
    backup: yes
  notify: restart php-fpm

- name: Create Nginx virtual host
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: Create web-root directory
  file:
    path: /var/www/{{ domain_name }}
    state: directory

- name: Upload files
  template:
    src: "{{ item }}.j2"
    dest: /var/www/{{ domain_name }}/{{ item }}.php
  with_items:
    - index
    - mysql
    - mssql
    - memcached
